export const COPY = {
  LANDING: {
    headline: "From blank page to job-ready resume \u2014 in 3 minutes.",
    subheadline: "No Word. No design skills. No confusion. Just type and download.",
    trustLine: "Built for India. Works in Hindi, Gujarati, Marathi, and English.",
    supportingLine: "Made for freshers, engineers, diploma holders, and working professionals.",
    primaryCta: "Build My Resume",
    secondaryCta: "Try Mock Interview",
  },
  BUILDER: {
    headline: "Build your resume step by step.",
    supportText: "Never made a resume before? Perfect. This is built for you.",
    formHelper: "Just fill what you know. We will handle the rest.",
    summaryHelper: "Tell us about yourself. We will write it professionally.",
    successMessage: "Your summary is ready. You can edit any part of it.",
    emptyState: "Start with your basic details. Your resume preview will appear here.",
    helpers: {
      name: "Use your full name as it appears on certificates.",
      title: "Example: Mechanical Engineer, Data Center Project Engineer, HVAC Technician.",
      location: "City and state are enough. Example: Mumbai, Maharashtra.",
      experience: "Write what you did, tools used, and results achieved.",
      skills: "Add technical skills, software tools, and site/project skills.",
      projects: "Mention project type, your role, and measurable work.",
      achievements: "Add awards, targets achieved, safety records, or project milestones.",
    }
  },
  TEMPLATES: {
    headline: "Choose your resume look.",
    supportText: "All formats are clean, professional, and ATS-friendly.",
    recommendationNote: "Not sure which to pick? Classic ATS works for most jobs.",
    cta: "Use This Template",
  },
  UPLOAD: {
    headline: "Already have a resume?",
    supportText: "Upload it. We will find weak areas and improve it.",
    instruction: "Upload PDF or DOCX. Keep the file under the allowed size.",
    cta: "Upload Resume",
    successMessage: "Resume uploaded. We are ready to scan it.",
    errorMessage: "We could not read this file. Try another PDF or DOCX.",
  },
  DOWNLOAD: {
    cta: "Download Resume",
    successMessage: "Your resume is ready.",
    nextStep: "Now check how ready it is for your target job.",
    secondaryCta: "Check ATS Score",
  },
  ATS: {
    headline: "Find out if your resume will reach a human.",
    explanation: "Many companies use software to filter resumes before anyone reads them.",
    scoreLine: (score: number) => `Your resume scored ${score}/100. Here is exactly what to fix.`,
    lowScore: "Score below 50? Fix these points before applying.",
    midScore: "You are close. Improve these areas to increase your chances.",
    highScore: "Score above 80? You are ready to apply.",
    cta: "Improve My Resume",
  },
  JOB_MATCH: {
    headline: "Paste any job. Know if your resume is ready.",
    supportText: "Stop applying blindly. See what is missing first.",
    resultMessage: (score: number) => `You are ${score}/100 ready for this job.`,
    missingKeywords: "Add these keywords to match the job better.",
    cta: "Check Job Match",
  },
  INTERVIEW: {
    headline: "Practice before the real interview.",
    supportText: "Answer real interview-style questions based on your role and resume.",
    languageHelper: "Choose the language you want to speak in.",
    resultLanguageHelper: "Choose the language you want your feedback in.",
    difficultyHelper: "Start easy. Build confidence.",
    warmupMessage: "Relax. There are no trick questions here. Just speak naturally.",
    silencePrompt: "Take your time. Speak when ready.",
    finalQuestionPrompt: "Almost there \u2014 one last question.",
    completionMessage: "Well done. Your interview is complete.",
    ctaStart: "Start Interview",
    ctaNext: "Next Question",
    ctaSkip: "Skip Question",
  },
  INTERVIEW_RESULT: {
    headline: "Here is how you did \u2014 and how to get better.",
    lowScore: "Score below 50? That is okay. Practice again with these tips.",
    midScore: "You are close. Improve your structure and examples.",
    highScore: "Great work. You are interview-ready.",
    encouragement: "Most users improve in the second round.",
    ctaRetry: "Practice Again",
    ctaTips: "View Tips",
  },
  DASHBOARD: {
    welcome: "Welcome back.",
    supportText: "Here is your progress so far.",
    headline: "Your career readiness at a glance.",
    completionHelper: "Complete your profile to unlock better results.",
    nextStep: "Next, scan your resume against a job description.",
    emptyState: "No activity yet. Start by creating or uploading your resume.",
    recentActivity: "Recent Activity",
    actions: {
      build: "Build Resume",
      upload: "Upload Resume",
      checkAts: "Check ATS Score",
      startInterview: "Start Interview",
    }
  },
  PROFILE: {
    headline: "Profile Settings",
    supportText: "Manage your personal details and preferences.",
    referralTitle: "Your NextStep Referral Link",
    referralDesc: "Share with friends and earn free ATS scans.",
    whatsappShare: "Share via WhatsApp",
    ctaSave: "Save Changes",
  },
  SHARE: {
    cta: "Share on WhatsApp",
    helperText: "Share with friends and unlock free scans.",
    successMessage: "Shared successfully. Thanks for helping others get job-ready.",
  },
  TRUST: {
    privacy: "Your data stays private. We never sell your information.",
    builtBy: "Built in India, for India.",
    founderLine: "Built by someone who understands engineering and project-site careers.",
    supportLine: "Need help? Reach us on WhatsApp.",
    links: {
      privacy: "Privacy Policy",
      terms: "Terms",
      contact: "Contact",
      support: "Support",
    }
  },
  ERRORS: {
    generic: "Oops! Something went wrong. Please try again.",
    slowInternet: "This is taking a little longer than usual. Please wait.",
    micDenied: "Microphone access is needed for voice interview.",
    timeout: "Your session timed out. Continue from where you left off.",
    uploadError: "We could not upload this file. Please try again.",
    invalidFileType: "Please upload a PDF or DOCX file.",
    paymentFailed: "Payment was not completed. You can try again safely.",
    loginError: "We could not log you in. Please check your details and try again.",
    emptyField: "Please fill this field to continue.",
  },
  LOADING: {
    resumeGeneration: "Building your resume...",
    atsScan: "Scanning your resume...",
    resumeImprovement: "Improving your resume...",
    jobMatch: "Checking your job readiness...",
    interviewSetup: "Setting up your interview...",
    resultGeneration: "Preparing your results...",
    pdfDownload: "Preparing your PDF...",
    paymentVerification: "Confirming your payment...",
  },
  BUTTONS: {
    RESUME: {
      build: "Build Resume",
      upload: "Upload Resume",
      scan: "Scan Resume",
      save: "Save Resume",
      improve: "Improve Resume",
      download: "Download Resume",
    },
    ATS: {
      check: "Check ATS Score",
      improve: "Improve ATS Score",
      viewSuggestions: "View Suggestions",
    },
    JOB_MATCH: {
      check: "Check Job Match",
      improve: "Improve for This Job",
    },
    INTERVIEW: {
      start: "Start Interview",
      next: "Next Question",
      skip: "Skip Question",
      viewResults: "View Results",
      practiceAgain: "Practice Again",
    },
    ACCOUNT: {
      signUp: "Sign Up",
      logIn: "Log In",
      logOut: "Log Out",
      saveChanges: "Save Changes",
    },
    PAYMENT: {
      buyResume: "Buy Resume Pack",
      buyInterview: "Buy Interview Pack",
      buyJobReady: "Buy Job Ready Pack",
    },
    SHARING: {
      shareWhatsApp: "Share on WhatsApp",
    }
  }
};
